wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.1
    code_path: code/0.py
    framework: huggingface
    huggingface_version: 2.4.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.11
    start_time: 1634406429
    t:
      1:
      - 1
      - 5
      - 9
      - 11
      2:
      - 1
      - 5
      - 9
      - 11
      4: 3.7.11
      5: 0.12.1
      6: 2.4.1
      8:
      - 5
